export interface ModelJudgment {
  model: string;
  score: number; // 0-100
  reasoning: string;
  // GonkaRouter's completion response `id` field, e.g. "chatcmpl-xxxx" - the
  // per-inference proof-of-decentralization the challenge brief asks the UI
  // to display ("Always display the Gonka Request ID to prove the 'Truth'
  // wasn't generated by a centralized server"). Prefixed "stub-" when this
  // judgment came from the local heuristic fallback (gonka/router.ts) rather
  // than a real GonkaRouter call, so the UI can't present a fabricated
  // judgment as if it were verifiably decentralized.
  request_id: string;
}

export interface GonkaEvaluation {
  judgments: ModelJudgment[];
  base_score: number; // average across judgments
  model_agreement: number; // 0-100, higher = models agree more
  // Deterministic script check (gonka/languageCheck.ts): did the agent reply
  // in the language it was asked in? Surfaced per scenario so the dashboard
  // can flag the "English-only agent wearing a translation layer" case
  // directly, rather than leaving it implicit in a lower score.
  replied_in_language: boolean;
}
